// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
// / await Firebase.initializeApp(
// /   options: DefaultFirebaseOptions.currentPlatform,
// / );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCGfDwAR_gZDofU-JDUdyGtrAFfH1GJ9I',
    appId: '1:15287948422:web:cded32bffb54ecbff76d07',
    messagingSenderId: '15287948422',
    projectId: 'qdev17-app1',
    authDomain: 'qdev17-app1.firebaseapp.com',
    storageBucket: 'qdev17-app1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5EJMdyHwEVEUMPRv7aqy1Q3_ivn8pYP8',
    appId: '1:15287948422:android:862a2e8e53afb6b3f76d07',
    messagingSenderId: '15287948422',
    projectId: 'qdev17-app1',
    storageBucket: 'qdev17-app1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxI9DiRoFzZjoCJvX3-EkrQvaIpNLhnj4',
    appId: '1:15287948422:ios:367e06d8fb6ce5e7f76d07',
    messagingSenderId: '15287948422',
    projectId: 'qdev17-app1',
    storageBucket: 'qdev17-app1.firebasestorage.app',
    iosBundleId: 'com.example.app1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxI9DiRoFzZjoCJvX3-EkrQvaIpNLhnj4',
    appId: '1:15287948422:ios:367e06d8fb6ce5e7f76d07',
    messagingSenderId: '15287948422',
    projectId: 'qdev17-app1',
    storageBucket: 'qdev17-app1.firebasestorage.app',
    iosBundleId: 'com.example.app1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCGfDwAR_gZDofU-JDUdyGtrAFfH1GJ9I',
    appId: '1:15287948422:web:c7060086fe24b5c6f76d07',
    messagingSenderId: '15287948422',
    projectId: 'qdev17-app1',
    authDomain: 'qdev17-app1.firebaseapp.com',
    storageBucket: 'qdev17-app1.firebasestorage.app',
  );
}
